name: 'Manage artifact labels in Unify'
description: 'Create, update, and remove labels on existing artifacts in CloudBees Unify.'

branding:
  icon: 'command'
  color: 'purple'

inputs:
  cloudbees-url:
    description: 'CloudBees Unify URL.'
    required: false
    default: "https://api.cloudbees.io"
  artifact-id:
    description: 'The unique identifier of an artifact.'
    required: true
  labels:
    description: 'A comma-separated list of artifact labels.'
    required: true
  operation:
    description: 'The type of action to be performed with labels of an artifact. ADD OR REMOVE are options available. ADD is used as default value.'
    required: false
    default: "ADD"

runs:
  using: "docker"
  image: "docker://public.ecr.aws/l7o7z1g8/actions/gha-label-artifact-version:main-d5b0352958f03a1d2fc2b481ba57f9c9f41844d2"
  env:
    CLOUDBEES_API_URL: ${{ inputs.cloudbees-url }}
    ARTIFACT_ID: ${{ inputs.artifact-id }}
    LABELS: ${{ inputs.labels }}
    OPERATION: ${{ inputs.operation }}
